export interface ManualControl { number: string; name: string; selector: string; }
export interface ManualScreenshot { id: string; chapter: string; route: string; state: string; role: string; language: 'en' | 'zh'; viewport: 'desktop' | 'mobile'; file: string; alt: string; controls: ManualControl[]; risk: 'none' | 'elevated' | 'high'; appCommit: string; openApi: string; }
const registrationControls: ManualControl[] = [
  { number: '1', name: 'Email', selector: '.auth-card > .form-group:has(> label:text-is("Email")) > input[type="email"]' },
  { number: '2', name: 'Verification code', selector: '.verification-code-row > input[placeholder="Verification code"]' },
  { number: '3', name: 'Send Code', selector: '.verification-code-row > button:text-is("Send Code")' },
  { number: '4', name: 'Password', selector: '.form-group:has(> label:text-is("Password (min 8 characters)")) input.password-input' },
  { number: '5', name: 'Hold to reveal password', selector: '.form-group:has(> label:text-is("Password (min 8 characters)")) .password-reveal-button' },
  { number: '6', name: 'Confirm Password', selector: '.form-group:has(> label:text-is("Confirm Password")) input.password-input' },
  { number: '7', name: 'Hold to reveal confirmation', selector: '.form-group:has(> label:text-is("Confirm Password")) .password-reveal-button' },
  { number: '8', name: 'Register', selector: '.auth-card > button.btn-signin:text-is("Register")' },
  { number: '9', name: 'Back to Login', selector: '.auth-card > .auth-footer button:text-is("Back to Login")' }
];
const recoveryControls: ManualControl[] = [
  { number: '1', name: 'Registered Email', selector: '.form-group:has(> label:text-is("Registered Email")) > input[type="email"]' },
  { number: '2', name: 'Image code', selector: '.captcha-inline > input[placeholder="Image code"]' },
  { number: '3', name: 'Refresh security image', selector: '.captcha-inline > .captcha-image-button' },
  { number: '4', name: 'Email verification code', selector: '.verification-code-row > input[placeholder="Verification code"]' },
  { number: '5', name: 'Send Code', selector: '.verification-code-row > button:text-is("Send Code")' },
  { number: '6', name: 'New Password', selector: '.form-group:has(> label:text-is("New Password")) input.password-input' },
  { number: '7', name: 'Hold to reveal password', selector: '.form-group:has(> label:text-is("New Password")) .password-reveal-button' },
  { number: '8', name: 'Reset Password', selector: '.auth-card > button.btn-signin:text-is("Reset Password")' },
  { number: '9', name: 'Back to Login', selector: '.auth-card > .auth-footer button:text-is("Back to Login")' }
];
const navigationControls: ManualControl[] = [{ number: '1', name: 'Language switcher', selector: '.topbar button' }, { number: '2', name: 'Notification bell', selector: '.topbar button:nth-of-type(2)' }, { number: '3', name: 'User avatar menu', selector: '.topbar button:nth-of-type(3)' }, { number: '4', name: 'Sidebar navigation', selector: '.sidebar a' }];
const capture = '2026-08-31 manual release v1.0.0';
const checked = 'v0.1.0 checked 2026-08-31';
const routes: Record<string, string> = { 'device-messages': '/device-messages', 'operation-logs': '/events', 'deactivated-accounts': '/deactivated-accounts' };
const d1Controls: Record<string, ManualControl[]> = {
  companies: [{ number: '1', name: 'Type filter', selector: '.content select' }, { number: '2', name: 'Search', selector: '.content input[placeholder*="Search"]' }, { number: '3', name: 'Create Company', selector: '.content button' }, { number: '4', name: 'Page size', selector: '.content select:last-of-type' }],
  'hubs-list-and-add': [{ number: '1', name: 'Status filter', selector: '.content select' }, { number: '2', name: 'Mode filter', selector: '.content select:nth-of-type(2)' }, { number: '3', name: 'Company filter', selector: '.content select:nth-of-type(3)' }, { number: '4', name: 'Add Hub', selector: '.content button' }],
  alarms: [{ number: '1', name: 'Status filter', selector: '.content select' }, { number: '2', name: 'Keyword search', selector: '.content input' }, { number: '3', name: 'Page size', selector: '.content select:last-of-type' }, { number: '4', name: 'Pagination input', selector: '.content input:last-of-type' }],
  accounts: [{ number: '1', name: 'Create Account', selector: '.content button' }, { number: '2', name: 'Role filter', selector: '.content select' }, { number: '3', name: 'Status filter', selector: '.content select:nth-of-type(2)' }, { number: '4', name: 'Page size', selector: '.content select:last-of-type' }]
  , 'device-messages': [{ number: '1', name: 'Hub SN search', selector: '.content input' }, { number: '2', name: 'Date range control', selector: '.content input:last-of-type' }]
  , 'operation-logs': [{ number: '1', name: 'Type filter', selector: '.content .toolbar > select.control' }, { number: '2', name: 'Keyword', selector: '.content .toolbar > input.search-control' }, { number: '3', name: 'Date range (From/To)', selector: '.content .toolbar > .event-date-picker:has(input[placeholder="From"])' }]
  , notifications: [{ number: '1', name: 'Mark all read', selector: '.content button' }, { number: '2', name: 'Notification item', selector: '.content button:nth-of-type(2)' }]
  , announcements: [{ number: '1', name: 'Create announcement', selector: '.content button' }, { number: '2', name: 'Announcement item action', selector: '.content button:nth-of-type(2)' }]
  , dashboard: [{ number: '1', name: 'KPI card', selector: '.content .kpi-card' }, { number: '2', name: 'Role label', selector: '.role-badge' }, { number: '3', name: 'Recent Events', selector: '.timeline' }, { number: '4', name: 'View All', selector: '.content .view-all-button' }]
  , 'deactivated-accounts': [{ number: '1', name: 'Company filter', selector: '.content select' }, { number: '2', name: 'Keyword search', selector: '.content input' }]
  , permissions: [{ number: '1', name: 'Role members link', selector: '.content .link-button' }, { number: '2', name: 'Edit role', selector: '.content button' }]
  , settings: [{ number: '1', name: 'Save Changes', selector: '.content button' }, { number: '2', name: 'Profile field', selector: '.content input' }, { number: '3', name: 'Language selector', selector: '.content select' }, { number: '4', name: 'Change Password', selector: '.content button' }, { number: '5', name: 'Logout', selector: '.content button' }, { number: '6', name: 'Delete Account', selector: '.content button:last-of-type' }]
};
const pageShots: ManualScreenshot[] = Object.keys(routes).map((id) => ({ id, chapter: 'guide/' + id, route: routes[id], state: 'authenticated list or landing state', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/pages/' + id + '.png', alt: id + ' controls', controls: d1Controls[id] || controls, risk: ['hub-remote-config', 'settings', 'permissions'].includes(id) ? 'high' : 'none', appCommit: capture, openApi: checked }));
export const screenshotManifest: ManualScreenshot[] = [
  { id: 'login', chapter: 'getting-started/login', route: '/login', state: 'login form', role: 'anonymous', language: 'en', viewport: 'desktop', file: '/images/auth/login.png', alt: 'Login controls', controls: [{ number: '1', name: 'Email', selector: 'input[type=email]' }, { number: '2', name: 'Password', selector: 'input[type=password]' }, { number: '3', name: 'Remember me', selector: 'input[type=checkbox]' }, { number: '4', name: 'Sign In', selector: '.btn-signin' }, { number: '5', name: 'Create Account', selector: 'button:text("Create Account")' }, { number: '6', name: 'Forgot Password', selector: 'button:text("Forgot Password?")' }], risk: 'none', appCommit: capture, openApi: checked },
  { id: 'register', chapter: 'getting-started/registration', route: '/login', state: 'registration form', role: 'anonymous', language: 'en', viewport: 'desktop', file: '/images/auth/register.png', alt: 'Registration: 1 Email, 2 verification code, 3 Send Code, 4 password, 5 reveal, 6 confirmation, 7 reveal confirmation, 8 Register, 9 Back to Login', controls: registrationControls, risk: 'none', appCommit: capture, openApi: checked },
  { id: 'recovery', chapter: 'getting-started/password-recovery', route: '/login', state: 'recovery form', role: 'anonymous', language: 'en', viewport: 'desktop', file: '/images/auth/recovery.png', alt: 'Password recovery: 1 registered email, 2 image code, 3 refresh image, 4 email code, 5 Send Code, 6 new password, 7 reveal, 8 Reset Password, 9 Back to Login', controls: recoveryControls, risk: 'none', appCommit: capture, openApi: checked },
  { id: 'navigation', chapter: 'getting-started/navigation-and-permissions', route: '/dashboard', state: 'authenticated shell', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/navigation/navigation.png', alt: 'Application shell controls', controls: navigationControls, risk: 'none', appCommit: capture, openApi: checked },
  { id: 'dashboard', chapter: 'guide/dashboard', route: '/dashboard', state: 'dashboard summary', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/dashboard/dashboard.png', alt: 'Dashboard controls', controls: d1Controls.dashboard, risk: 'none', appCommit: capture, openApi: checked },
  { id: 'company-create', chapter: 'guide/companies', route: '/companies', state: 'Create Company modal', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/companies/company-create.png', alt: 'Create Company form', controls: [{ number: '1', name: 'Company name', selector: '.modal-body .form-group:nth-of-type(1) input' }, { number: '2', name: 'Company type', selector: '.modal-body .form-group:nth-of-type(2) select' }, { number: '3', name: 'Logo input', selector: '#companyLogoFile' }, { number: '4', name: 'Save', selector: '.modal-footer .btn-primary' }], risk: 'elevated', appCommit: capture, openApi: checked },
  { id: 'company-edit', chapter: 'guide/companies', route: '/companies', state: 'Edit Company modal', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/companies/company-edit.png', alt: 'Edit Company form', controls: [{ number: '1', name: 'Company name', selector: '.modal-body .form-group:nth-of-type(1) input' }, { number: '2', name: 'Company type', selector: '.modal-body .form-group:nth-of-type(2) select' }, { number: '3', name: 'Logo input', selector: '#companyLogoFile' }, { number: '4', name: 'Save Changes', selector: '.modal-footer .btn-primary' }], risk: 'elevated', appCommit: capture, openApi: checked },
  { id: 'company-detail-employees', chapter: 'guide/companies', route: '/companies', state: 'Company detail and employees', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/companies/company-detail-employees.png', alt: 'Company details and employee controls', controls: [{ number: '1', name: 'Edit company', selector: '.detail-card .btn' }, { number: '2', name: 'Add Employee', selector: '.employees-card .btn-primary' }, { number: '3', name: 'Edit employee', selector: '.employees-card .btn-s[title="Edit"]' }, { number: '4', name: 'Transfer company owner', selector: '.employees-card .owner-transfer-action' }, { number: '5', name: 'Associated Hubs', selector: '.detail-actions .btn-outline' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'company-employee-form', chapter: 'guide/companies', route: '/companies', state: 'Add Employee modal', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/companies/company-employee-form.png', alt: 'Add employee form', controls: [{ number: '1', name: 'Employee email', selector: '.modal-body .form-group:nth-of-type(1) input' }, { number: '2', name: 'Employee role', selector: '.modal-body .form-group:nth-of-type(2) select' }, { number: '3', name: 'Employee phone', selector: '.modal-body .form-group:nth-of-type(3) input' }, { number: '4', name: 'Save employee', selector: '.modal-footer .btn-primary' }], risk: 'elevated', appCommit: capture, openApi: checked },
  { id: 'company-owner-transfer', chapter: 'guide/companies', route: '/companies', state: 'Owner transfer confirmation', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/companies/company-owner-transfer.png', alt: 'Company owner transfer confirmation', controls: [{ number: '1', name: 'Transfer consequence', selector: '.confirm-modal .confirm-message' }, { number: '2', name: 'Cancel transfer', selector: '.confirm-modal .btn-outline' }, { number: '3', name: 'Confirm transfer', selector: '.confirm-modal .btn-primary' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'company-employee-actions', chapter: 'guide/companies', route: '/companies', state: 'Employee detail delete and status actions', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/companies/company-employee-actions.png', alt: 'Company employee row actions', controls: [{ number: '1', name: 'Employee detail', selector: '.employees-card .btn-s[title="Detail"]' }, { number: '2', name: 'Delete employee', selector: '.employees-card .btn-s[title="Delete"]' }, { number: '3', name: 'Enable or disable employee', selector: '.employees-card .toggle-action .toggle-slider' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'company-employee-detail', chapter: 'guide/companies', route: '/companies', state: 'Employee detail view', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/companies/company-employee-detail.png', alt: 'Company employee detail view', controls: [{ number: '1', name: 'Back to company', selector: '.card + button.btn-outline' }], risk: 'none', appCommit: capture, openApi: checked },
  { id: 'company-employee-delete-confirm', chapter: 'guide/companies', route: '/companies', state: 'Delete employee confirmation', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/companies/company-employee-delete-confirm.png', alt: 'Delete company employee confirmation', controls: [{ number: '1', name: 'Deletion consequence', selector: '.confirm-modal .confirm-message' }, { number: '2', name: 'Cancel employee deletion', selector: '.confirm-modal .btn-outline' }, { number: '3', name: 'Confirm employee deletion', selector: '.confirm-modal .btn-primary' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'company-delete-confirm', chapter: 'guide/companies', route: '/companies', state: 'Soft delete company confirmation', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/companies/company-delete-confirm.png', alt: 'Soft delete company confirmation', controls: [{ number: '1', name: 'Soft delete consequence', selector: '.confirm-modal .confirm-message' }, { number: '2', name: 'Cancel company deletion', selector: '.confirm-modal .btn-outline' }, { number: '3', name: 'Confirm company deletion', selector: '.confirm-modal .btn-primary' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'hub-add-step-1', chapter: 'guide/hubs-list-and-add', route: '/hubs', state: 'Add Hub Power and Connect', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-add-step-1.png', alt: 'Add Hub Power and Connect step', controls: [{ number: '1', name: 'Power and Connect step', selector: '.steps .step:nth-of-type(1)' }, { number: '2', name: 'Ready Continue', selector: '.add-hub-step-panel .btn-primary' }, { number: '3', name: 'Close wizard', selector: '.add-hub-modal .modal-close' }], risk: 'elevated', appCommit: capture, openApi: checked },
  { id: 'hub-add-step-2', chapter: 'guide/hubs-list-and-add', route: '/hubs', state: 'Add Hub serial number', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-add-step-2.png', alt: 'Add Hub serial number step', controls: [{ number: '1', name: 'Hub serial number', selector: '#add-hub-sn' }, { number: '2', name: 'Back', selector: '.wizard-actions .btn-outline' }, { number: '3', name: 'Next', selector: '.wizard-actions .btn-primary' }, { number: '4', name: 'Close wizard', selector: '.add-hub-modal .modal-close' }], risk: 'elevated', appCommit: capture, openApi: checked },
  { id: 'hub-add-step-3', chapter: 'guide/hubs-list-and-add', route: '/hubs', state: 'Add Hub company and confirmation', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-add-step-3.png', alt: 'Add Hub company selection and confirmation', controls: [{ number: '1', name: 'Company search', selector: '#add-hub-company-search' }, { number: '2', name: 'No Company', selector: '.add-hub-company-options > button.person-option' }, { number: '3', name: 'Company option', selector: '.add-hub-company-options > button.person-option:nth-of-type(2)' }, { number: '4', name: 'Load more companies', selector: '[data-testid="add-hub-company-load-more"]' }, { number: '5', name: 'Confirm Add Hub', selector: '.confirm-panel .btn-primary' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'hub-list-actions', chapter: 'guide/hubs-list-and-add', route: '/hubs', state: 'Hub list filters and row actions', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-list-actions.png', alt: 'Hub list filters and row actions', controls: [{ number: '1', name: 'Status filter', selector: '.toolbar select:nth-of-type(1)' }, { number: '2', name: 'Mode filter', selector: '.toolbar select:nth-of-type(2)' }, { number: '3', name: 'Company filter', selector: '.toolbar select:nth-of-type(3)' }, { number: '4', name: 'Serial number search', selector: '.toolbar .search-control' }, { number: '5', name: 'Add Hub', selector: '.toolbar .btn-primary' }, { number: '6', name: 'Sub-device count', selector: '.hub-device-count' }, { number: '7', name: 'Arm or Disarm', selector: '.arm-actions .arm-icon-button' }, { number: '8', name: 'Details', selector: '.hub-list-card button[title="Detail"]' }, { number: '9', name: 'Assign', selector: '.hub-list-card button[title="Assign"]' }, { number: '10', name: 'Delete', selector: '.hub-list-card button[title="Delete"]' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'hub-assign-modal', chapter: 'guide/hubs-list-and-add', route: '/hubs', state: 'Assign Hub modal', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-assign-modal.png', alt: 'Assign Hub company and person controls', controls: [{ number: '1', name: 'Company', selector: '.modal-body .form-group:nth-of-type(3) select' }, { number: '2', name: 'Assign to person', selector: '.person-combobox input' }, { number: '3', name: 'Cancel assignment', selector: '.modal-footer .btn-outline' }, { number: '4', name: 'Save assignment', selector: '.modal-footer .btn-primary' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'hub-delete-confirm', chapter: 'guide/hubs-list-and-add', route: '/hubs', state: 'Delete Hub confirmation', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-delete-confirm.png', alt: 'Delete Hub confirmation', controls: [{ number: '1', name: 'Unbinding consequence', selector: '.confirm-modal .confirm-message' }, { number: '2', name: 'Cancel deletion', selector: '.confirm-modal .btn-outline' }, { number: '3', name: 'Confirm deletion', selector: '.confirm-modal .btn-primary' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'hub-detail-main', chapter: 'guide/hub-detail', route: '/hubs', state: 'Hub details', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-detail-main.png', alt: 'Hub detail controls', controls: [{ number: '1', name: 'Hub details tab', selector: '.sub-tabs button:nth-of-type(2)' }, { number: '2', name: 'Remote Config tab', selector: '.sub-tabs button:nth-of-type(3)' }, { number: '3', name: 'Sub-devices tab', selector: '.sub-tabs button:nth-of-type(4)' }, { number: '4', name: 'Edit Hub', selector: '.detail-card .card-header .btn' }, { number: '5', name: 'Disarm control', selector: '.arm-btn-row .btn:nth-of-type(1)' }, { number: '6', name: 'Custom arm mode', selector: '.arm-btn-row .btn:nth-of-type(4)' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'hub-detail-logs', chapter: 'guide/hub-detail', route: '/hubs', state: 'Hub logs available', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-detail-logs.png', alt: 'Hub logs and export controls', controls: [{ number: '1', name: 'Download log', selector: '.log-table .btn-outline' }, { number: '2', name: 'Delete log', selector: '.log-table .btn-danger' }, { number: '3', name: 'Get Log', selector: '.detail-card:has(.log-table) .card-header .btn-primary' }, { number: '4', name: 'Export Messages to Excel', selector: '.detail-card:has(> button.btn-primary) > button.btn-primary' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'hub-log-delete-confirm', chapter: 'guide/hub-detail', route: '/hubs', state: 'Delete Hub log confirmation', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-log-delete-confirm.png', alt: 'Delete Hub log confirmation', controls: [{ number: '1', name: 'Delete log warning', selector: '.el-message-box__message' }, { number: '2', name: 'Cancel deletion', selector: '.el-message-box__btns button:nth-of-type(1)' }, { number: '3', name: 'Confirm deletion', selector: '.el-message-box__btns button:nth-of-type(2)' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'hub-remote-config-main', chapter: 'guide/hub-remote-config', route: '/hubs', state: 'Remote Config user management and App User cards', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-remote-config-main.png', alt: 'Remote Config user management and App User controls', controls: [{ number: '1', name: 'User Management', selector: '[aria-controls="remote-config-users"]' }, { number: '2', name: 'Invite role', selector: '.invite-role-select' }, { number: '3', name: 'Room scope', selector: '.invite-room-trigger' }, { number: '4', name: 'Invite email', selector: '.invite-email' }, { number: '5', name: 'Send Invitation', selector: '.invite-user-button' }, { number: '6', name: 'App User section', selector: '[aria-controls="remote-config-app-users"]' }, { number: '7', name: 'Configure App User', selector: '[data-test="app-user-card"] .app-user-configure' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'hub-remote-config-invite', chapter: 'guide/hub-remote-config', route: '/hubs', state: 'Invite User form', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-remote-config-invite.png', alt: 'Remote Config invite form', controls: [{ number: '1', name: 'Invite role', selector: '.invite-role-select' }, { number: '2', name: 'Room scope', selector: '.invite-room-trigger' }, { number: '3', name: 'Invite email', selector: '.invite-email' }, { number: '4', name: 'Send Invitation', selector: '.invite-user-button' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'hub-app-user-settings', chapter: 'guide/hub-remote-config', route: '/hubs', state: 'App User notification, phone, PIN, and transfer settings', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-app-user-settings.png', alt: 'App User settings controls', controls: [{ number: '1', name: 'Notification methods', selector: '.method-group input[type="checkbox"]' }, { number: '2', name: 'Phone number', selector: '[data-test="app-user-phone-row"] input' }, { number: '3', name: 'Remove phone', selector: '[data-test="app-user-delete-phone"]' }, { number: '4', name: 'Add phone', selector: '[data-test="app-user-phone-actions"] .btn-outline' }, { number: '5', name: 'Configure PIN', selector: '[data-test="app-user-pin-section"] .btn-outline' }, { number: '6', name: 'Transfer target', selector: '[data-test="app-user-transfer-select"]' }, { number: '7', name: 'Transfer Super Admin', selector: '[data-test="app-user-transfer"]' }, { number: '8', name: 'Save user settings', selector: '[data-test="app-user-save"]' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'hub-app-user-pin', chapter: 'guide/hub-remote-config', route: '/hubs', state: 'App User PIN dialog', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-app-user-pin.png', alt: 'App User PIN dialog', controls: [{ number: '1', name: 'Fixed PIN prefix', selector: '.pin-dialog .pin-code-row input:nth-of-type(1)' }, { number: '2', name: 'PIN digits', selector: '.pin-dialog [data-test="app-user-pin-digit"]' }, { number: '3', name: 'Cancel PIN', selector: '.pin-dialog .btn-outline' }, { number: '4', name: 'Save PIN draft', selector: '.pin-dialog .btn-primary' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'hub-super-admin-transfer-confirm', chapter: 'guide/hub-remote-config', route: '/hubs', state: 'Super Admin transfer confirmation', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-super-admin-transfer-confirm.png', alt: 'Super Admin transfer confirmation', controls: [{ number: '1', name: 'Transfer consequence', selector: '.confirm-modal .confirm-message' }, { number: '2', name: 'Cancel transfer', selector: '.confirm-modal .btn-outline' }, { number: '3', name: 'Confirm transfer', selector: '.confirm-modal .btn-primary' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'hub-maintenance', chapter: 'guide/hub-remote-config', route: '/hubs', state: 'Maintenance SSH and restart controls', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-maintenance.png', alt: 'Maintenance SSH and restart controls', controls: [{ number: '1', name: 'Maintenance section', selector: '[aria-controls="remote-config-maintenance"]' }, { number: '2', name: 'SSH toggle', selector: '#remote-config-maintenance .toggle-switch' }, { number: '3', name: 'Restart Hub', selector: '#remote-config-maintenance .btn-danger' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'hub-restart-confirm', chapter: 'guide/hub-remote-config', route: '/hubs', state: 'Restart Hub confirmation', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-restart-confirm.png', alt: 'Restart Hub confirmation', controls: [{ number: '1', name: 'Restart warning', selector: '.confirm-modal .confirm-message' }, { number: '2', name: 'Cancel restart', selector: '.confirm-modal .btn-outline' }, { number: '3', name: 'Confirm restart', selector: '.confirm-modal .btn-primary' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'hub-subdevices-list', chapter: 'guide/hub-subdevices', route: '/hubs', state: 'Sub-device list with filters', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-subdevices-list.png', alt: 'Sub-device filters and row actions', controls: [{ number: '1', name: 'Type filter', selector: '.subdevice-toolbar select:nth-of-type(1)' }, { number: '2', name: 'Model filter', selector: '.subdevice-toolbar select:nth-of-type(2)' }, { number: '3', name: 'Status filter', selector: '.subdevice-toolbar select:nth-of-type(3)' }, { number: '4', name: 'Serial number search', selector: '.subdevice-search' }, { number: '5', name: 'Sub-device detail', selector: '.subdevice-table .actions button[title="Detail"]' }, { number: '6', name: 'Edit sub-device', selector: '.subdevice-table .actions button[title="Edit"]' }, { number: '7', name: 'Delete sub-device', selector: '.subdevice-table .actions button[title="Delete"]' }], risk: 'elevated', appCommit: capture, openApi: checked },
  { id: 'hub-subdevice-detail', chapter: 'guide/hub-subdevices', route: '/hubs', state: 'Sub-device detail', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-subdevice-detail.png', alt: 'Sub-device detail and delete control', controls: [{ number: '1', name: 'Delete Device', selector: '.detail-card .btn-danger' }, { number: '2', name: 'Back to Sub-devices', selector: 'button.btn.btn-outline' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'hub-subdevice-edit-room', chapter: 'guide/hub-subdevices', route: '/hubs', state: 'Edit existing sub-device name and room', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-subdevice-edit-room.png', alt: 'Sub-device edit name and room form', controls: [{ number: '1', name: 'Device name', selector: '.modal-body .form-group:nth-of-type(1) input' }, { number: '2', name: 'Room selection', selector: '.modal-body .form-group:nth-of-type(4) select' }, { number: '3', name: 'Create room name', selector: '.modal-body .form-group:nth-of-type(5) input' }, { number: '4', name: 'Cancel edit', selector: '.modal-footer .btn-outline' }, { number: '5', name: 'Confirm edit', selector: '.modal-footer .btn-primary' }], risk: 'elevated', appCommit: capture, openApi: checked },
  { id: 'hub-subdevice-delete-confirm', chapter: 'guide/hub-subdevices', route: '/hubs', state: 'Delete sub-device confirmation', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-subdevice-delete-confirm.png', alt: 'Delete sub-device confirmation', controls: [{ number: '1', name: 'Delete warning', selector: '.confirm-modal .confirm-message' }, { number: '2', name: 'Cancel deletion', selector: '.confirm-modal .btn-outline' }, { number: '3', name: 'Confirm deletion', selector: '.confirm-modal .btn-primary' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'hub-add-subdevice-allowed', chapter: 'guide/hub-subdevices', route: '/hubs', state: 'Add Sub-device disarmed entry', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-add-subdevice-allowed.png', alt: 'Disarmed Sub-device registration entry', controls: [{ number: '1', name: 'Registration step', selector: '.add-sub-card .steps .step:nth-of-type(1)' }, { number: '2', name: 'Confirm LED blinking', selector: '.add-sub-card .btn-primary' }, { number: '3', name: 'Exit registration mode', selector: '.add-sub-card .btn-danger' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'hub-add-subdevice-scan', chapter: 'guide/hub-subdevices', route: '/hubs', state: 'Sub-device registration scan result', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-add-subdevice-scan.png', alt: 'Sub-device registration scan and edit controls', controls: [{ number: '1', name: 'Scan progress', selector: '.add-sub-progress' }, { number: '2', name: 'Edit discovered sub-device', selector: '.add-sub-table .btn-outline' }, { number: '3', name: 'Next complete registration', selector: '.add-sub-card .btn-primary' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'hub-add-subdevice-edit', chapter: 'guide/hub-subdevices', route: '/hubs', state: 'Edit discovered sub-device', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-add-subdevice-edit.png', alt: 'Discovered sub-device edit and room form', controls: [{ number: '1', name: 'Device name', selector: '.modal-body .form-group:nth-of-type(1) input' }, { number: '2', name: 'Room selection', selector: '.modal-body .form-group:nth-of-type(4) select' }, { number: '3', name: 'Create room name', selector: '.modal-body .form-group:nth-of-type(5) input' }, { number: '4', name: 'Cancel edit', selector: '.modal-footer .btn-outline' }, { number: '5', name: 'Confirm edit', selector: '.modal-footer .btn-primary' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'hub-add-subdevice-confirm', chapter: 'guide/hub-subdevices', route: '/hubs', state: 'Sub-device registration ready to complete', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-add-subdevice-confirm.png', alt: 'Sub-device registration completion control', controls: [{ number: '1', name: 'Complete registration', selector: '.add-sub-result-panel .btn-primary' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'hub-add-subdevice-armed-blocked', chapter: 'guide/hub-subdevices', route: '/hubs', state: 'Add Sub-device blocked while Hub armed', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/hubs/hub-add-subdevice-armed-blocked.png', alt: 'Armed Hub blocks Sub-device registration', controls: [{ number: '1', name: 'Hub List tab', selector: '.sub-tabs button:nth-of-type(1)' }, { number: '2', name: 'Hub Detail tab', selector: '.sub-tabs button:nth-of-type(2)' }, { number: '3', name: 'Add Sub-device tab', selector: '.sub-tabs button:nth-of-type(5)' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'alarm-detail-new', chapter: 'guide/alarms', route: '/alarms', state: 'New alarm detail and processing history', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/alarms/alarm-detail-new.png', alt: 'New alarm detail, history, and Start Processing controls', controls: [{ number: '1', name: 'Processing notes', selector: '#alarmProcessNote' }, { number: '2', name: 'Start Processing', selector: '.modal.wide .modal-footer .btn-primary' }, { number: '3', name: 'Cancel detail', selector: '.modal.wide .modal-footer .btn-outline' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'alarm-detail-processing', chapter: 'guide/alarms', route: '/alarms', state: 'Processing alarm with image attachment control', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/alarms/alarm-detail-processing.png', alt: 'Processing alarm image attachment and Close controls', controls: [{ number: '1', name: 'Processing notes', selector: '#alarmProcessNote' }, { number: '2', name: 'Choose image', selector: 'label[for="alarmCloseImage"]' }, { number: '3', name: 'Close Alarm', selector: '.modal.wide .modal-footer .btn-primary' }, { number: '4', name: 'Cancel detail', selector: '.modal.wide .modal-footer .btn-outline' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'alarm-closed-list', chapter: 'guide/alarms', route: '/alarms', state: 'Closed alarm list state', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/alarms/alarm-closed-list.png', alt: 'Closed alarm list filter and detail controls', controls: [{ number: '1', name: 'Status filter', selector: '.toolbar select' }, { number: '2', name: 'Keyword search', selector: '.toolbar input' }, { number: '3', name: 'Alarm detail card', selector: '.alarm-card' }], risk: 'elevated', appCommit: capture, openApi: checked },
  { id: 'account-status-toggle', chapter: 'guide/accounts', route: '/accounts', state: 'Account list and direct status toggle', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/accounts/account-status-toggle.png', alt: 'Account filters, actions, and status toggle', controls: [{ number: '1', name: 'Role filter', selector: '.toolbar select:nth-of-type(1)' }, { number: '2', name: 'Status filter', selector: '.toolbar select:nth-of-type(2)' }, { number: '3', name: 'Account search', selector: '.toolbar .search-control' }, { number: '4', name: 'View account', selector: '.account-table button[title="Detail"]' }, { number: '5', name: 'Edit account', selector: '.account-table button[title="Edit"]' }, { number: '6', name: 'Enable or disable account', selector: '.account-table .toggle-action' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'account-create', chapter: 'guide/accounts', route: '/accounts', state: 'Create platform account', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/accounts/account-create.png', alt: 'Create Account fields and confirmation controls', controls: [{ number: '1', name: 'Account name', selector: '.account-form-fields .form-group:nth-of-type(1) input' }, { number: '2', name: 'Email', selector: '.account-form-fields .form-group:nth-of-type(2) input' }, { number: '3', name: 'Company', selector: '.account-form-fields .form-group:nth-of-type(3) select' }, { number: '4', name: 'Role', selector: '.account-form-fields .form-group:nth-of-type(4) select' }, { number: '5', name: 'Hold to reveal password', selector: '.account-form-fields .password-reveal-button' }, { number: '6', name: 'Confirm creation', selector: '.create-confirm-button' }, { number: '7', name: 'Cancel creation', selector: '.form-actions .btn-outline' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'account-detail', chapter: 'guide/accounts', route: '/accounts', state: 'Non-super-admin account detail', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/accounts/account-detail.png', alt: 'Account detail and Reset Password action', controls: [{ number: '1', name: 'Reset Password', selector: '.account-detail-card .info-item:nth-of-type(5) .btn-outline' }, { number: '2', name: 'Back to account list', selector: '.account-detail-card .form-actions .btn-outline' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'account-reset-password', chapter: 'guide/accounts', route: '/accounts', state: 'Administrator password reset dialog', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/accounts/account-reset-password.png', alt: 'Reset Password dialog', controls: [{ number: '1', name: 'New password', selector: '.reset-password-modal .form-group:nth-of-type(1) input' }, { number: '2', name: 'Confirm new password', selector: '.reset-password-modal .form-group:nth-of-type(2) input' }, { number: '3', name: 'Hold to reveal password', selector: '.reset-password-modal .password-reveal-button' }, { number: '4', name: 'Cancel reset', selector: '.reset-password-modal .modal-footer .btn-outline' }, { number: '5', name: 'Reset Password', selector: '.reset-password-modal .modal-footer .btn-primary' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'account-edit', chapter: 'guide/accounts', route: '/accounts', state: 'Edit account dialog', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/accounts/account-edit.png', alt: 'Edit Account fields and save controls', controls: [{ number: '1', name: 'Account name', selector: '.modal-body .form-group:nth-of-type(1) input' }, { number: '2', name: 'Read-only email', selector: '.modal-body .form-group:nth-of-type(2) input[readonly]' }, { number: '3', name: 'Company', selector: '.modal-body .form-group:nth-of-type(3) select' }, { number: '4', name: 'Role', selector: '.modal-body .form-group:nth-of-type(4) select' }, { number: '5', name: 'Cancel edit', selector: '.modal-footer .btn-outline' }, { number: '6', name: 'Save Changes', selector: '.modal-footer .btn-primary' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'permission-role-list', chapter: 'guide/permissions', route: '/permissions', state: 'Role list with member and configuration actions', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/permissions/permission-role-list.png', alt: 'Permission role members and configuration actions', controls: [{ number: '1', name: 'Role members', selector: '.permission-table .link-button' }, { number: '2', name: 'Configure role permissions', selector: '.permission-table .btn-s' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'permission-tree-edit', chapter: 'guide/permissions', route: '/permissions', state: 'Platform-super-admin permission tree edit', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/permissions/permission-tree-edit.png', alt: 'Permission tree parent and child controls', controls: [{ number: '1', name: 'Expand module', selector: '.permission-node-head' }, { number: '2', name: 'Module parent permission', selector: '.tree-parent' }, { number: '3', name: 'Child permission', selector: '.tree-child' }, { number: '4', name: 'Save permissions', selector: '.form-actions .btn-primary' }, { number: '5', name: 'Cancel editing', selector: '.form-actions .btn-outline' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'notification-single-read', chapter: 'guide/notifications', route: '/notifications', state: 'Single notification marked read', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/notifications/notification-single-read.png', alt: 'Single notification read state', controls: [{ number: '1', name: 'Mark All Read', selector: '.notifications-header .btn-outline' }, { number: '2', name: 'Read notification', selector: '.notification-item.read' }, { number: '3', name: 'Unread notification', selector: '.notification-item:not(.read)' }], risk: 'elevated', appCommit: capture, openApi: checked },
  { id: 'notification-mark-all-progress', chapter: 'guide/notifications', route: '/notifications', state: 'Mark All Read progress', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/notifications/notification-mark-all-progress.png', alt: 'Mark All Read progress dialog', controls: [{ number: '1', name: 'Progress dialog', selector: '.read-progress-modal' }, { number: '2', name: 'Progress title', selector: '.read-progress-modal strong' }, { number: '3', name: 'Unread remaining count', selector: '.read-progress-modal p' }], risk: 'elevated', appCommit: capture, openApi: checked },
  { id: 'notification-mark-all-complete', chapter: 'guide/notifications', route: '/notifications', state: 'All notifications marked read', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/notifications/notification-mark-all-complete.png', alt: 'All notifications read state', controls: [{ number: '1', name: 'Mark All Read', selector: '.notifications-header .btn-outline' }, { number: '2', name: 'Read notification', selector: '.notification-item.read' }], risk: 'elevated', appCommit: capture, openApi: checked },
  { id: 'announcement-create', chapter: 'guide/announcements', route: '/announcements', state: 'Create announcement dialog', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/announcements/announcement-create.png', alt: 'Create announcement dialog', controls: [{ number: '1', name: 'Announcement title', selector: '.announcement-form-body input' }, { number: '2', name: 'Announcement content', selector: '.announcement-form-body textarea' }, { number: '3', name: 'Cancel announcement', selector: '.announcement-form-modal .modal-footer .btn-outline' }, { number: '4', name: 'Save announcement', selector: '.announcement-form-confirm' }], risk: 'elevated', appCommit: capture, openApi: checked },
  { id: 'announcement-edit', chapter: 'guide/announcements', route: '/announcements', state: 'Edit announcement dialog', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/announcements/announcement-edit.png', alt: 'Edit announcement dialog', controls: [{ number: '1', name: 'Announcement title', selector: '.announcement-form-body input' }, { number: '2', name: 'Announcement content', selector: '.announcement-form-body textarea' }, { number: '3', name: 'Cancel announcement', selector: '.announcement-form-modal .modal-footer .btn-outline' }, { number: '4', name: 'Save announcement', selector: '.announcement-form-confirm' }], risk: 'elevated', appCommit: capture, openApi: checked },
  { id: 'announcement-delete-action', chapter: 'guide/announcements', route: '/announcements', state: 'Announcement maintenance actions', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/announcements/announcement-delete-action.png', alt: 'Announcement create edit and direct delete actions', controls: [{ number: '1', name: 'New Announcement', selector: '.announcement-publish' }, { number: '2', name: 'Edit announcement', selector: '.announcement-edit' }, { number: '3', name: 'Delete announcement', selector: '.announcement-delete' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'settings-change-password', chapter: 'guide/settings', route: '/settings', state: 'Change Password form', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/settings/settings-change-password.png', alt: 'Settings Change Password fields', controls: [{ number: '1', name: 'Current password', selector: '.settings-layout > .settings-card:nth-child(2) .form-group:nth-of-type(2) input' }, { number: '2', name: 'New password', selector: '.settings-layout > .settings-card:nth-child(2) .form-group:nth-of-type(3) input' }, { number: '3', name: 'Confirm new password', selector: '.settings-layout > .settings-card:nth-child(2) .form-group:nth-of-type(4) input' }, { number: '4', name: 'Hold to reveal password', selector: '.settings-layout > .settings-card:nth-child(2) .password-reveal-button' }, { number: '5', name: 'Update Password', selector: '.settings-layout > .settings-card:nth-child(2) .btn-primary' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'settings-overview', chapter: 'guide/settings', route: '/settings', state: 'Profile, language, and account deletion entry', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/settings/settings-overview.png', alt: 'Settings profile language and delete entry controls', controls: [{ number: '1', name: 'Save Changes', selector: '.settings-layout > .settings-card:nth-child(1) .btn-primary' }, { number: '2', name: 'Language selector', selector: '.settings-layout > .settings-card:nth-child(3) .language-control' }, { number: '3', name: 'Delete My Account', selector: '.settings-layout > .danger-card .btn-danger' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'settings-delete-account-confirm', chapter: 'guide/settings', route: '/settings', state: 'Delete current account confirmation', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/settings/settings-delete-account-confirm.png', alt: 'Delete current account confirmation', controls: [{ number: '1', name: 'Deletion consequence', selector: '.confirm-modal .modal-body p' }, { number: '2', name: 'Cancel deletion', selector: '.confirm-modal .btn-outline' }, { number: '3', name: 'Confirm deletion', selector: '.confirm-modal .btn-primary' }], risk: 'high', appCommit: capture, openApi: checked },
  { id: 'settings-logout', chapter: 'guide/settings', route: '/settings', state: 'Logout action', role: 'platform-super-admin fixture', language: 'en', viewport: 'desktop', file: '/images/settings/settings-logout.png', alt: 'Settings Logout control', controls: [{ number: '1', name: 'Logout', selector: '.settings-layout > .settings-card:nth-child(4) .btn-outline' }], risk: 'elevated', appCommit: capture, openApi: checked },
  ...pageShots
];
